name: Upload deployment metrics to Data Fridge
inputs:
  deploy-env:
    description: Deployment environment
    required: true
    default: "development"
  release-notes:
    description: Release notes
    required: true
    default: "latest"
  token:
    description: Datafridge auth token
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Send stats
      run: >-
        curl -i --retry 10 --retry-delay 32 -X "POST" "https://end0qr3fuyyt7nr.m.pipedream.net"
        -H "Authorization: Bearer ${{ inputs.token }}"
        -H 'Content-Type: application/json'
        -d $'{
        "entity": "Pandora",
        "product": "Content Agent Experience Backend",
        "tribe": "Vendor Enablement",
        "environment": "${{ inputs.deploy-env }}",
        "tag": "latest",
        "application": "Content Agent Experience Backend",
        "timestamp": "'"$(date -u +'%FT%TZ')"'",
        "release_notes": "${{ inputs.release-notes }}"
        }'
      shell: bash
