name: "Test"
on: ["push"]

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
    - name: Test
      run: echo "test"
    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%FT%TZ')"
    - name: Send stats
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://end0qr3fuyyt7nr.m.pipedream.net'
        bearerToken: 'Bearer XXX'
        escapeData: 'true'
        data: >-
          {
            "entity": "Pandora",
            "tribe": "New Business",
            "timestamp": "${{ steps.timestamp.outputs.timestamp }}",
            "product": "Content Agent Experience Backend",
            "application": "Content Agent Experience Backend",
            "environment": "staging",
            "tag": "latest",
            "release_notes": "test release notes"
          }
