name: "Test"
on: ["push"]

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - name: Test
        run: echo "test"

      - uses: actions/checkout@master
      # DataFridge only accepts the long name
      - name: Set deploy environment name
        id: get-deployment-name
        env:
          DEPLOY_STG: stg
        run: |
          case $DEPLOY_STG in
           prod)
             echo "::set-output name=deploy_env::production"
             ;;
           stg)
             echo "::set-output name=deploy_env::staging"
             ;;
           dev)
             echo "::set-output name=deploy_env::development"
             ;;
           esac

      - name: Get commits range
        id: commits
        run: echo "::set-output name=commits::$(git log --abbrev-commit --pretty=oneline ${{ github.sha }})"

      - name: Upload metrics
        uses: ./.github/actions/upload-metrics
        with:
          deploy-env: ${{ steps.get-deployment-name.outputs.deploy_env }}
          release-notes: ${{ steps.commits.outputs.commits }}
